kind: Service
apiVersion: v1
metadata:
  name: backend-service
spec:
  selector:
    name: userbackend
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: LoadBalancer
---
#  yaml for deployment of flask backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userbackend
spec:
  selector:
    matchLabels:
      name: userbackend
  replicas: 1
  template:
    metadata:
      labels:
        name: userbackend
    spec:
      containers:
      - name: userbackend
        image: ramyaj876/userbackend:1
        ports:
        - containerPort: 5001
---
