apiVersion: apps/v1
kind: Deployment
metadata:
  name: userbackend
spec:
  selector:
    matchLabels:
      name: userbackend
  replicas: 1
  template:
    metadata:
      labels:
        name: userbackend
    spec:
      containers:
      - name: userbackend
        image: userbackend
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    name: userbackend      
  ports:
  - name: userbackend
    port: 5001
    protocol: TCP
  type: LoadBalancer
